version: "3.8"

services:
  api:
    build: ${PWD}/docker/dev
    container_name: api
    hostname: api
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - CACHE_HOST=redis
      - CACHE_PORT=6379
    tty: true
    volumes:
      - ./:/app/
    depends_on:
      - redis

  redis:
    image: "redis:7.2-alpine"
    container_name: redis
    hostname: redis
    ulimits:
      memlock: -1
    cpuset: "2"
    ports:
      - "6379:6379"

