version: "3.8"

services:
  api:
    build: ${PWD}/packages/app
    container_name: api
    hostname: api
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - CACHE_HOST=dragonfly
      - CACHE_PORT=6379
    tty: true
    depends_on:
      - dragonfly

  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    container_name: dragonfly
    hostname: dragonfly
    platform: linux/arm64
    ulimits:
      memlock: -1
    cpuset: "2"
    ports:
      - "6379:6379"

